### ISSUE TITLE
More customizable shortcuts?

### ISSUE THREAD

**Issue by kard32** [TriliumNext/Trilium#1082]
Hi - loving Trilium so far! I was wondering - are there any plans to have more customizable shortcuts? (For example, I'd like a shortcut to set "type", i.e. Book; or to go to a specific note, like my todo list; setting a note as readOnly or archived; duplicate; etc)

**Comment by zadam** [comment]
Hi, more shortcuts will be created in time, but there's a limit ...

However I want to provide a way to be able to bind keyboard shortcut to a script which can then trigger anything you want (e.g. setting as readOnly etc.)

Btw, there is already a way to define a keyboard shortcut for accessing a particular note - define a label `keyboardShortcut` with e.g. `ctrl+alt+x`

Then reload the frontend/restart the app and then the shortcut should activate given note.

**Comment by kard32** [comment]
Ah - just tested the keyboard shortcut for a particular note. Just tested it, and it works! Thank you.
Gotcha re script keyboard shortcut - that definitely would be awesome.
Thanks again for the great work on this

**Comment by JeordyR** [comment]
@zadam On this topic, is there currently or are there any plans to add keyboard shortcuts or editor features for in-lien code blocks, tasks lists, etc. that don't currently have any?

Ex, I heavily make use of in-line code blocks, since text within 1 `'s doesn't achieve this, highlight + clicking the code button gets it done, but a keybind for that code style option would be great to avoid having click the style. 

Similar for task list, since `- [ ]` doesn't work, a keybind to insert a task would be awesome.

**Comment by zadam** [comment]
> Ex, I heavily make use of in-line code blocks, since text within \`'s doesn't achieve this, highlight + clicking the code button gets it done

If you type `` `text` `` then the "text" is auto-formatted into inline code, does this work for you?

**Comment by JeordyR** [comment]
> > Ex, I heavily make use of in-line code blocks, since text within `'s doesn't achieve this, highlight + clicking the code button gets it done
> 
> If you type `` `text` `` then the "text" is auto-formatted into inline code, does this work for you?

Did some more testing, and it does work, so ignore that comment. It works if you do `` ` `` then text, then another `` ` ``, just not if you do both `` ` ``'s then go back and fill text in between them.

**Comment by ultrafine** [comment]
Is it possible to set a keyboard shortcut for changing themes? I would like to cycle through different themes quickly without multiple clicks, and I was wondering if there are any ways to do so.
