### ISSUE TITLE
Shortcut for ckeditor's edit block menu

### ISSUE THREAD

**Issue by leeyaunlong** [TriliumNext/Trilium#1141]
can you add the shortcut to popup the ckeditor's edit block menu?
because some funcitons in block menu have the shortcut , but I want to quick access others(inline note , etc).

**Comment by koutto** [comment]
would indeed be great to have shortcuts/hotkeys for some formatting like "inline code", "block code" and so on. I think it is dependent of Ckeditor, and maybe there is a plugin for that

**Comment by zadam** [comment]
Checkout https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html

Things like inline/block code can be triggered in markdown fashion via typing \`something\` and \`\`\`

**Comment by psybustermk2** [comment]
It's not complete though. The checkbox (to-do list) does not work when doing [ ] or [x].

**Comment by stgolem** [comment]
There is already 0.47.5 available. How can we trigger "edit block" menu from keyboard?

**Comment by abitofevrything** [comment]
@zadam was referring to the check box list, not the keyboard shortcuts

**Comment by WACrown** [comment]
@code-ink-space This is a good idea! However, in version 0.59.1, the multi-tag function will cause the shortcut key to not work. I made some changes:
`api.bindGlobalShortcut("alt+q", function(){
    console.log("alt+q");
    let edit_block_buttons = document.querySelectorAll(".ck.ck-button.ck-block-toolbar-button");
        for (let item of edit_block_buttons) {
            console.log(item);
            if(!item.getAttribute("class").includes("ck-hidden")){
                item.click();
                continue;
            }
        }
});`

**Comment by WACrown** [comment]
@code-ink-space This is a good idea! However, in version 0.59.1, the multi-tag function will cause the shortcut key to not work. I made some changes:
```
api.bindGlobalShortcut("alt+q", function(){
    console.log("alt+q");
    let edit_block_buttons = document.querySelectorAll(".ck.ck-button.ck-block-toolbar-button");
        for (let item of edit_block_buttons) {
            console.log(item);
            if(!item.getAttribute("class").includes("ck-hidden")){
                item.click();
                continue;
            }
        }
});
```

**Comment by eliandoran** [comment]
This is now indirectly supported via slash commands, where you can type /h2, /h3, /paragraph to apply to the current block. Most of the features have a corresponding slash command.
