### ISSUE TITLE
Shift+Del doesnot cut to clipboard

### ISSUE THREAD

**Issue by cidious** [TriliumNext/Trilium#1325]
Trilium 0.44.9 for Linux

Pressing Shift+Del on text selection does not cut it to clipboard, just deletes the selection.
Although Shift+Ins inserts the clipboard content OK.

BTW both Ctrl+X and Ctrl+V work OK.

There is nothing relevant in the log file.

Is it possible to fix the Shift+Del behavior?

Thank you.

**Comment by zadam** [comment]
Hi, this seems to be caused by CKEditor not recognizing this keyboard shortcuts so it would have to be fixed there first.

Other input fields not controlled by CKEditor (e.g. note title) seem to behave correctly.

**Comment by cidious** [comment]
Hi, thanks for the answer,

well it's weird because the official CKEditor's documentation says it should support this keystroke:
https://ckeditor.com/docs/ckeditor4/latest/features/shortcuts.html

```
Cut, Copy and Paste
    Ctrl+X, Shift+Del – Cuts a text fragment to clipboard.
```

**Comment by zadam** [comment]
The docs refer to CKEditor 4 while Trilium uses CKEditor 5 which is complete reimplementation so I wouldn't be surprised if there are bugs/omissions compared to v4.

**Comment by cidious** [comment]
Just read the docs on 5 and realized that they removed this keystroke which gets me really surprised.
Any professional text editor either supports these (Shift+Del, Ctrl+Ins, Shift+Ins), or allows to map keys.
Is it possible to map this keystroke?

**Comment by cidious** [comment]
tried to change the Keyboard Shortcuts in the Options: cutNotesToClipboard: Shift+Delete
No luck. It keeps using Ctrl+X.

**Comment by zadam** [comment]
Hi, cutNotesToClipboard refers to a tree operation (cutting whole notes into clipboard), not to text editing.

Currently, it is not possible to bind custom text editor keyboard shortcuts.
