### ISSUE TITLE
why doesnt this have basic auto-update yet - when will it?

### ISSUE THREAD

**Issue by needhelpfulanswers-spectrumchat** [TriliumNext/trilium#1341]
why doesnt this have basic auto-update yet - when will it?

**Comment by zadam** [comment]
Auto update is not a high priority feature at this point. Contributions are welcome of course.

**Comment by needhelpfulanswers-spectrumchat** [comment]
well it should be a high priority because not having it made this thing delete all our notes....

???

no other software/apps does that when it auto-updates....

**Comment by zadam** [comment]
Update (of course) does not delete any notes.

**Comment by blumpcus** [comment]
@needhelpfulanswers-spectrumchat 
I've noticed that in the past day or two, you've made several posts with a similar ineffective tone and a rather striking lack of care when demanding for features or requiring help in solving issues from others. 

I'm sure you can relate; if I walked into your community and demanded something, regardless of the inherent value of the request, you would not want to support me, especially if I came with nothing to offer you. This is precisely what you're doing.  
In this instance, you're on github, a community driven by the free effort & free time of programmers and the contributions of others. It would benefit you tremendously to communicate with a little more compassion & care. 

Don't forget, no one here owes you anything, however, if you're reasonable enough, someone will be willing to help you along the way. 

Also, please don't speak for the rest of us. I've been self-updating for over a year now without a single issue.

Back to your original problem, I'm sorry if you've lost your notes but that will likely have nothing to do with a Trilium update. 
_document.db_, which houses all of your notes, is located in a different location (If you're on Windows, hit _windows sign + r_ on your keyboard, type in _%appdata%\trilium-data_). This file and it's directory do not get affected by updates. 
Also, within that folder, you will find another folder named _backup_ which contains 3 other backup files that will likely have what you need to recover (_backup-daily, backup-monthly, backup-weekly_). You will need to copy the file you want back into _%appdata%\trilium-data_ and rename it to _document.db_ before opening Trilium again. 

If I were you, I would start backing up regularly, as you should with any other software. Data loss is a nonissue with preventative action.

**Comment by meichthys** [comment]
If you use docker, you can use an auto-update container like [Watchtower](https://registry.hub.docker.com/r/containrrr/watchtower) or [Ouroboros](https://github.com/pyouroboros/ouroboros) to auto-update your Trilium container :)
