### ISSUE TITLE
Bug: Different date format is misleading

### ISSUE THREAD

**Issue by TriplEight** [TriliumNext/trilium#2091]
Linux app v 0.47.5

Almost everywhere, including day template, I have i.e. `#dateNote=yyyy-mm-dd`
But in a Book Template and other calendar forms there's a weird `mm/dd/yyyy`

**Comment by zadam** [comment]
Hi, can you clarify what you mean by "book template and other calendar forms"? Ideally screenshots ...

Thanks.

**Comment by zadam** [comment]
Hi, can you explain what you mean by "book template and other calendar forms"? Ideally screenshots ...

Thanks.

**Comment by Mirwaisse** [comment]
I think he's talking about the book reviews in the demo Document:
![image](https://user-images.githubusercontent.com/25323123/127557385-7f67e0fb-ddc8-4710-8313-4d5994803ae8.png)
The date format is tied to the user's OS date format:
![image](https://user-images.githubusercontent.com/25323123/127557449-7d35ae67-c542-42cd-8e1a-d24b2c4b83ac.png)

If I change the date format of Windows, it also changes the date format of the (promoted) attributes of the book review.
(but the actual attributes still has the YYYY-MM-DD format)
![image](https://user-images.githubusercontent.com/25323123/127558011-eafd4cc8-0051-4822-a1ba-f05fd47f9645.png)

**Comment by zadam** [comment]
I see, yes. These widgets are coming from chrome and they respect the OS locale. But trilium has a fixed format independent from current locale ...

**Comment by TriplEight** [comment]
Is there a way to stabilize it (and maybe create a setting that takes some default) throughout Trilium? :pray:

**Comment by zadam** [comment]
I guess you could force a particular locale for the process, but I haven't researched it (`LC_*` env. variables in linux etc.)

**Comment by good-praxis** [comment]
For me the days and month are flipped specifically, what's the reason of using the system locale, but enforcing a specific placeholder for trilium? Or did I misunderstand something?

**Comment by zadam** [comment]
> For me the days and month are flipped specifically, what's the reason of using the system locale

This is not something I can influence. These are native widgets and they use whatever system uses.

**Comment by viq** [comment]
Seems relevant to this ticket, I was testing things, and while setting `LC_ALL=en_DK.utf8` makes trilium display date fields as `dd/mm/yyyy`, setting `LC_TIME=en_DK.utf8` (which is recommended; setting `LC_ALL` is discouraged, e.g. [here](https://wiki.debian.org/Locale)) seems to be ignored and date fields are still `mm/dd/yyyy`.

**Comment by eliandoran** [comment]
This is already customizable in Options -> Language & Region -> Language.
