### ISSUE TITLE
Shortcut for "To-Do list", instead of typing "[ ]"

### ISSUE THREAD

**Issue by WantToLearnJapanese** [TriliumNext/Trilium#2123]

**Comment by ecodiv** [comment]
In addition to rather than instead of, I hope, because I quite like the [ ] syntax

**Comment by WantToLearnJapanese** [comment]
> In addition to rather than instead of, I hope, because I quite like the [ ] syntax

Yes! My intention was exactly that!

**Comment by Myzel394** [comment]
@WantToLearnJapanese do you have any suggestions?
