### ISSUE TITLE
[Feature Request] Manually create revision immediately.

### ISSUE THREAD

**Issue by YYMMYB** [TriliumNext/trilium#2147]
add an API to create revision.

**Comment by zadam** [comment]
I added an option to define a shortcut for this:

![image](https://user-images.githubusercontent.com/617641/200680839-a1253db3-4f03-439f-a881-5c53ebee4ede.png)

Otherwise, there's no UI for that.

**Comment by Nriver** [comment]
Thanks, that's even better!

**Comment by eliandoran** [comment]
We already have "Save revision" in the note context menu, so I believe we're good.
