### ISSUE TITLE
(Bug report) Images not resized in revision menu; causes menu breakage

### ISSUE THREAD

**Issue by sigaloid** [TriliumNext/Trilium#2216]
**Describe the bug**
The revision menu is broken by a wide image (resizing it does not work)

**Confirm that you have searched for existing issues in the issue tracker by adding an "x" between the brackets below**
- [x] I have searched for duplicate bugs in the issue tracker

**To Reproduce**
1. Add wide image 
2. Go to revision menu
3. See wide and broken menu

**Expected behavior**
The image should be resized even in the revision menu (whether it be according to the resizing in the actual note, or just automatically)

**Screenshots**
![image](https://user-images.githubusercontent.com/69441971/136707018-a6728ec3-911a-40dc-b643-9a2c5b96713b.png)

**Platform (please complete the following information):**

 - What operating system?: Linux desktop
 - Syncing
 - Version: 0.47.8 and 0.48.0

**Additional context**
It seems that the "Note revisions" menu does not respect resizing. It should automatically resize if the image is larger than the width of the menu.

**Comment by zadam** [comment]
Thanks for reporting this bug, fixed.
