### ISSUE TITLE
(Bug report) migration failed, crashing hard

### ISSUE THREAD

**Issue by enzofoucaud** [TriliumNext/Trilium#2233]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.1-beta

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

W10

### Expected Behavior

I want to migrate 0.47.8 to 0.48.X but i have this following error

### Actual Behavior

```
App db version is 185, while db version is 183. Migration needed.
DB size: 1757 KB
App HTTP server starting up at port 8080
{
  "appVersion": "0.48.1-beta",
  "dbVersion": 185,
  "syncVersion": 21,
  "buildDate": "2021-10-12T22:42:48+02:00",
  "buildRevision": "64a3a8b561f614a1940551bb3feb9e035f7cb475",
  "dataDirectory": "/home/node/trilium-data",
  "clipperProtocolVersion": "1.0"
}
CPU model: Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz, logical cores: 2 freq: 2194 Mhz
Listening on port 8080
Created backup at /home/node/trilium-data/backup/backup-before-migration.db
Attempting migration to version 184
Migration with JS module
Becca (note cache) load took 4ms
ERROR: error during migration to version 184: SqliteError: attempt to write a readonly database
    at /usr/src/app/src/services/sql.js:176:31
    at wrap (/usr/src/app/src/services/sql.js:212:18)
    at Object.execute (/usr/src/app/src/services/sql.js:176:12)
    at migrate (/usr/src/app/src/services/migration.js:73:17)
    at async Object.migrateIfNecessary (/usr/src/app/src/services/migration.js:112:9)
    at async initDbConnection (/usr/src/app/src/services/sql_init.js:41:5)
ERROR: migration failed, crashing hard
```

**Comment by JustinWuCN** [comment]
@enzofoucaud How to solve this problem? 
I have same problem, too.

**Comment by zadam** [comment]
They had permission problem, so `chmod 700 document.db` would solve it. Depends if that's your issue as well.

**Comment by yllekz** [comment]
Hello, I attempted ``chmod 700 document.db`` on the file but it did not solve this issue for me. Any other ideas or suggestions?

**Comment by zadam** [comment]
The nuclear option is `chmod 777 document.db`, otherwise it's not a permission issue.
