### ISSUE TITLE
Shortcut for changing block-types

### ISSUE THREAD

**Issue by JaCoB1123** [TriliumNext/Trilium#2234]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

Hi, 

first off: I've only been using Trilium for about a week and have been loving it after testing multiple note apps in the last months. The last one I used was VSCode with the Foam extensions - so mostly just writing Markdown.

The thing that surprises me often is that I can't remove the headlines "#"-signs easily. Sometimes it works and convert's the headline to a regular paragraph, sometimes I just keep creating more Headlines. I'd love to see a Hotkey to toggle between Headlines and ideally also the various blocks (e.g. to convert text to code or to set the language of an existing code block). It might be a single shortcut that opens the block-popup (or something similar but more keyboard-friendly).

If something like this exists and I just missed it, please just tell me where to find it.

Thanks

**Comment by abitofevrything** [comment]
This happens most of the time because of copy pasting. If there is a non-paragraph line break at the end of a header, pressing enter before that line break will result in a new paragraph being created, but with header font size. Just make sure there are no newlines at the end of your headers when you press enter.

**Comment by JaCoB1123** [comment]
Minimal example of my issue:

```html
<h2>First Heading</h2><h2>Second Heading but should be Paragraph</h2>
```

## First method

1. When I try to convert the second h2 to a regular paragraph by pressing backspace at the start of the second h2, it results in a single h2 with both texts:

```html
<h2>First HeadingSecond Heading but should be Paragraph</h2>
```

2. If i press Enter afterwards with my cursor still between "Heading" and "Second", I return to the original state.

## Second method

If I press enter at the end of the first heading, I get a regular paragraph: 

```html
<h2>First Heading</h2><p></p><h2Second Heading but should be Paragraph</h2>
```

But if I press Delete afterwards, the empty paragraph is deleted and I return to the original state.
The only way to force the second heading into a paragraph is to add some text to the empty paragraph and delete afterwards.

## Proposal

If we could use Tab & Shift-Tab to increase/decrease the Heading level like we can with lists, that would be nice. I think that wouldn't be a surprising behavior either.

**Comment by abitofevrything** [comment]
Maybe ctrl+> or ctrl+< like Google docs and word for font size would make more sense (since tab and shift+tab is ready bound to indentation level)
