### ISSUE TITLE
Link map in v0.48.2 does not show links and relations

### ISSUE THREAD

**Issue by adamcodemaker** [TriliumNext/Trilium#2251]
First of all good job guys. I am really impressed how new version looks 👍 

I noticed that Note Map works differently comparing to previous version.
v 47.8
![image](https://user-images.githubusercontent.com/25587877/138182490-4e24f456-6dee-47b8-8c54-10f809889fc6.png)
v48.2
![image](https://user-images.githubusercontent.com/25587877/138182613-8e7d06f4-f6d0-41f1-b8f8-91a80db04d33.png)
Is this intended?
I am in the middle of reorganizing my notes based on tags and relations and link map will be very important to me.
As well as "What links here" which is missing in new version.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. This is a bug/omission, I added a proper display of relations back in there.
