### ISSUE TITLE
[Question] Security public-internet my sync server

### ISSUE THREAD

**Issue by dawidmachon** [TriliumNext/Trilium#2260]
Hi, I want only ask if Trilium web server is secured to be exposed to public internet?

**Comment by machond** [comment]
Thanks guys, I am not that kind of paranoid, but you know... Long, unique
pass everywhere. But, as you said, if there is no holes in login page, then
im good to go.

I will close when in pc, or anyone can close it :)



sob., 23 paź 2021, 23:34 użytkownik zadam ***@***.***>
napisał:
