### ISSUE TITLE
Basic PKGBUILD For Arch Users

### ISSUE THREAD

**Issue by OnyxAzryn** [TriliumNext/Trilium#235]
Hey, I love this project and I have been using it daily for the past few months.  As an Arch user, I always wanted an installation method for Trilium, so I decided to make one.  The following code can be used with makepkg to generate an package that can be installed with Pacman and ran with a simple command. 

**Process:**
1. Copy and save the following code into a file entitled "PKGBUILD":
```
pkgname="trilium-bin"
pkgver=0.23.1
pkgrel=2
pkgdesc="A hierarchical note taking application built on modern technologies."
depends=('python' 'make' 'gconf' 'libxss' 'nss' 'lib32-gcc-libs' 'gtk3')
arch=('x86_64')
url="https://github.com/zadam/trilium"
license=('AGPL')
source=("https://github.com/zadam/trilium/releases/download/v$pkgver/trilium-linux-x64-$pkgver.7z")
sha256sums=('4c3f2d2d62175bd400ce2914146b6c6b0af195e09454d348916fd27ecac76aaf')

package()
{
        export destdir="$pkgdir/"
        mkdir -p "$pkgdir/usr/share/trilium"
        mkdir -p "$pkgdir/usr/lib"
        mv trilium-linux-x64/libffmpeg.so trilium-linux-x64/libnode.so -t "$pkgdir/usr/lib"
        mv trilium-linux-x64/* "$pkgdir/usr/share/trilium"
        mkdir -p "$pkgdir/usr/bin"
        echo -e "#!/bin/sh\n/usr/share/trilium/trilium" > "$pkgdir/usr/bin/trilium"
        chmod +x "$pkgdir/usr/bin/trilium"
}
```
2. Then, run ``makepkg`` in the directory where the file is stored.
3. After the package is created, it can be installed with:
``pacman -U trilium-linux-x64-bin-0.23.1-1-x86_64.pkg.tar``
4. Finally, Trilium can be ran be simply typing ``trilium`` into a terminal, or by creating a shortcut in the user's desktop environment.

I wanted to bring this to your attention, as I saw there was some demand for an installable version of Trilium.  All that needs to be changed when Trilium updates to make this functional again is to change the "pkgver" variable to the new version and then overwrite the sha2 hash of the new binary.  Also, the package name will reflect this version change as well.  This is my first time creating a PKGBUILD file, so it may have some rough edges.  Particularity, I am not sure if installing it to the ``/usr/share`` directory is the best idea.  However, I installed it and it works well.  I hope you are doing well and I sincerely appreciate all of your work.

**Comment by zadam** [comment]
Hi OnyxDelta, unfortunately I'm not sure what to do with this. 

Assuming I can build this package on ubuntu, I'm very hesitant publishing packages which I can't even smoke test. Building for and supporting various distros is probably out of scope of what I can do. The only exception might be Ubuntu in the future since that's the distro I use so it's easy for me to test.

**Comment by OnyxDelta** [comment]
Oh, I am sorry for not specifying this, but I did not expect you to really do anything with it. I was posting it here for anyone who might want to use it to create a package themselves for Arch. If you want, you can feel free to add it to the Wiki, so it is public. In hindsight, this may not have been the best place to post this. I'm really sorry for the confusion.

**Comment by zadam** [comment]
Oh, I see, that makes it clear ...

Of course you're welcome to post it to AUR! If you do so, I can add a link pointing to it to the wiki.

**Comment by OnyxDelta** [comment]
Thank you very much.  I uploaded it and I will continue to update it when you release a new version:
https://aur.archlinux.org/packages/trilium-linux-x64-bin/
