### ISSUE TITLE
(Feature request) Support for linking or including specific chapters in notes

### ISSUE THREAD

**Issue by frapples** [TriliumNext/Trilium#2938]
### Describe feature

Recently I tried the beta version and the TOC function is very cooooool. 👍
With TOC, when users organize notes, the basic unit will be smaller. The basic unit used to be a note, and now the basic unit is a chapter in a note.
However, our "link" feature and "include notes" feature, the unit is still a note. How about if the unit of these two features can be refined to the chapters in the notes? 
In a note, the user can choose to link to a specific chapter of another note by typing @.  The "include notes" function is also similar.

**Comment by sigaloid** [comment]
Same issues: https://github.com/zadam/trilium/issues/1021 and linked

Perhaps the ToC plug-in will make it easier to implement though.

**Comment by zadam** [comment]
Yes, it's the same feature request, I will close this one to keep the discussion in one place.
