### ISSUE TITLE
(Feature request) Any plans for a plugin system?

### ISSUE THREAD

**Issue by DarthPleurotus** [TriliumNext/Trilium#2969]
### Describe feature

Trillium seems really flexible and extensible, and I'd love for it to be easy to use add-ons/customizations that other users have come up with. Are there any plans to create a system for users to submit plugins (as there are in Obsidian and Logseq, for example). I think that with a working plugin system and [mobile offline capabilities](https://github.com/zadam/trilium/issues/2970), Trillium would probably be the best of the three.

**Comment by DarthPleurotus** [comment]
Thanks for the list! 

I'd love for there to be a more refined system for sharing and installing scripts though. Simply sharing code snippets in a forum feels pretty inaccessible for many users.

**Comment by zadam** [comment]
Yeah, this idea has been floated around before (unfortunately can't find the issue where it was discussed in more detail), but nothing has been really done so far.

One problem is that it's a pretty big topic which needs quite a lot of work. It's also not clear how many plugin developers are there in the community, probably only just a couple.
