### ISSUE TITLE
Links without `http://` or protocol go to localhost

### ISSUE THREAD

**Issue by autumn-birds** [TriliumNext/Trilium#338]
Links without, e.g., `http://` prefixed will not open correctly in the current release (0.27.4) because, as far as I can guess, the Trilium internal browser thinks they're a relative link.

To reproduce this behavior, select some text, click the link icon, type `google.com` into the text box and hit enter. Then click on the link. You'll be taken (at least on my machine/setup, Windows 7 with Firefox) to `http://localhost:51429/google.com`.

It seems fairly obvious what's going on to me, but this is probably kind of counterintuitive for a lot of users and you might want to fix it.

**Comment by Dialga** [comment]
Cannot reproduce this.
