### ISSUE TITLE
(Bug report) Collapsing trilium sidebar in one browser window also collapses sidebar in all other browser windows

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Trilium#3698]
### Trilium Version

0.59.1

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10

### Description

This is an edge case for sure, but if using Trilium in multiple browser windows at the same time, collapsing the sidebar on one window will collapse the sidebar in all browser windows. 

![image](https://user-images.githubusercontent.com/10717998/224423465-2ade7d75-66e8-4360-a52a-e35c983b4c3b.png)

I know it's not a supported use case, but if there are multiple people logged into the web interface at the same time, this situation is unexpected.

Note: this does not affect the desktop app, just two browser instances of Trilium.

**Comment by zadam** [comment]
Yes, this is expected. Collapsed state is global and persisted (but not synced), therefore it affects all tabs.

**Comment by Nriver** [comment]
If you want more space for editing area, you can try this really cool widget https://github.com/SiriusXT/trilium-left-panel-auto-zoom. It `automatically widen note tree by moving your mouse`.
