### ISSUE TITLE
(Bug report) 'Save to Note' search button does not respect #inbox

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Trilium#3755]
### Trilium Version

0.59.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

This could be intended, but the 'Save to note' button in the search does not seem to respect the #inbox tag, and instead creates a calendar tree:
![image](https://user-images.githubusercontent.com/10717998/226706252-d18036fc-1373-4f10-88a5-e6c32dd053c9.png)

**Comment by zadam** [comment]
Hi, this is controlled by `#searchHome`, working similarly as `#inbox`.
