### ISSUE TITLE
(Bug report) Not possible to click links on note preview

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Trilium#3760]
### Trilium Version

0.59.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

When hovering over an internal link that links to a 'folder note' (one that has no content of its own but does have child notes), the popup preview nicely shows the child notes as links, but there's no way to click those links since the hovering popup goes away when trying to click them:

![image](https://user-images.githubusercontent.com/10717998/227232517-e3afdda4-61a5-432c-ae52-916a9dd18ae1.png)

**Comment by zadam** [comment]
The preview is meant to be a preview only. 

The links show up in the preview as links, because they are ... links. I don't think it's desirable to somehow hide that they are links.
