### ISSUE TITLE
Code Signing

### ISSUE THREAD

**Issue by iwoloschin** [TriliumNext/Trilium#380]
Is it possible to start signing Trilium releases?  In the below link you can see the popup that comes up after installing a new release (installed via homebrew).

https://electronjs.org/docs/tutorial/code-signing

I'll be honest, I have no idea how feasible this request is, but I figure it doesn't hurt to ask!

**Comment by zadam** [comment]
Frankly looks like too much work for too little benefit. Especially the fact that signing for both mac & windows will have to be done on their platforms respectively which is really inconvenient since I'm producing builds on linux for all platforms. Also Apple developer fee ...

**Comment by iwoloschin** [comment]
I figured that'd be the answer :).

Is it ok if we leave this open for a bit?  I can try to dig into how some other projects do the code signing and see if there's any ways to do it without paying the Apple Developer fee, or even without having access to macOS directly.

**Comment by technovangelist** [comment]
So if you trust the app to run locally you can sign it locally. You won't be able to send this to someone else (I think) but it will eliminate the popup on your machine. I created a script on my local machine with the following contents:

`#!/bin/env bash
codesign -s - -f /Applications/Trilium\ Notes.app/ --deep
codesign -s - -f /Applications/Trilium\ Notes.app/`

Not sure if codesign was part of the full electron or xcode dev tools, but when there is a new version, I can install and run trilsign on my mac and it signs the app. No more dialog.

**Comment by eliandoran** [comment]
This has been done on both Windows and macOS.
