### ISSUE TITLE
(Bug report) 'Shared Notes' note missing

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Trilium#3907]
### Trilium Version

0.59.4

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu

### Description

The 'Shared Notes' Node doesn't seem to exist anymore.
https://github.com/zadam/trilium/wiki/Sharing#seeing-all-shared-notes
I could have accidentally removed it on my instances, but I don't see a way to add it back.

**Comment by zadam** [comment]
Hi, try restarting your server - those "system" notes are check on startup and re-created if not existing.
