### ISSUE TITLE
(Feature request) Share and Navigation

### ISSUE THREAD

**Issue by passionate2023** [TriliumNext/Trilium#4169]
### Describe feature

1. Option to share the whole note for other users to view/search what we see in web application. basically the shared users should be able to view, search but should not have the privilege to edit/delete the notes of the entire notebook
2. type ahead with number of matches on typing and highlight text in search results in 1st level and second level navigation
navigation arrows to navigate the occurrences of the searched keyword in the notes when clicked via search results

**Comment by zadam** [comment]
Hi, could you please explain your points a bit?

1.  seems like you're describing the existing share feature?
2.  do you still talk about share feature? What is 1st level and 2nd level navigation?

**Comment by passionate2023** [comment]
1. not sure whether we have this feature. currently we can share a note or notes collection - however search is not available for the entire collection for the end user

2. for the second item, for example, just import a huge text in (app.simplenote.com) and search a keyword which has many occurrences in each file, see the display of results and 1st and 2nd level navigation with arrows (note: not with ctrl+f) but arrows will be available by default

Please go through the screenshot or give a try with the tool to understand it better

![image](https://github.com/zadam/trilium/assets/117767352/25f5abba-ae10-491b-833f-35106a715be2)

Thanks
