### ISSUE TITLE
(Feature Request) Embedding files in a note

### ISSUE THREAD

**Issue by Roger7890** [TriliumNext/trilium#4472]
### Trilium Version

0.62.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11

### Description

Hello, when I drag and drop a file onto a note, simple URLs are generated but the file is not integrated into the note to use the trilium video, pdf, audio, download... player.  Only images are integrated directly into the notes!

![Sélection_123](https://github.com/zadam/trilium/assets/145009879/564a749b-d2b1-43ac-af74-ee5313327d7f)

**Comment by zadam** [comment]
Hi, this is a feature request, not bug report.

**Comment by Lolabird** [comment]
A workaround for this is to drag and drop files in the note tree under the target note and then use "include note" to embed the file in that note.

**Comment by eliandoran** [comment]
See https://github.com/TriliumNext/trilium/issues/5040
