### ISSUE TITLE
(Bug report) Latest release can't open

### ISSUE THREAD

**Issue by qiaoyu-jzh** [TriliumNext/Trilium#4493]
### Trilium Version

0.62.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 home 19045.3693

### Description

latest release can't open .

**Comment by deajan** [comment]
Have you run the trilium executable from a command line ? If so, you can get the corresponding logs.
An empty bug report won't help much.
