### ISSUE TITLE
(Feature Request) A button to Update to the latest version 

### ISSUE THREAD

**Issue by thanayut1750** [TriliumNext/trilium#4586]
### Describe feature

Hey I just started using Trilium for note taking and I love it so far but today I just saw the new version update but I don't know how to do it Correctly(fear of my note will be lost) I would be nice if there is a feature for automatically update for you

Now here is my question
- how can I update the trilium server?
context:
- Now my trilium server is on the AWS lightsail instance.
![image](https://github.com/zadam/trilium/assets/28057767/e06de922-bf6b-48da-afb8-f2eda31705ff)

**Comment by JeanPluzo** [comment]
Hi,
I haven't played with the server version, but if you're on Linux, I would just stop the server (`systemctl stop trilium.server`), follow the instructions to install the server, and restart the server.
Since your data (`trilium-data`) is on your home directory it will stay untouched. But, as always, backup, backup, backup!

Regards,
J.

**Comment by thanayut1750** [comment]
> Hi, I haven't played with the server version, but if you're on Linux, I would just stop the server (`systemctl stop trilium.server`), follow the instructions to install the server, and restart the server. Since your data (`trilium-data`) is on your home directory it will stay untouched. But, as always, backup, backup, backup!
> 
> Regards, J.

so all of my note data is in the trilium-data folder right?

Thx. ill try.

**Comment by thanayut1750** [comment]
It work THANK YOU. @JeanPluzo 

Here is the step in case of someone have the same question.

1. stop the trilium service with ` sudo systemctl stop trilium.service `
2. `wget https://github.com/zadam/trilium/releases/download/<latest_version>/trilium-linux-x64-server-<latest_version>.tar.xz`
3. `tar -xvf trilium-linux-x64-server-[VERSION].tar.xz`
4. `sudo mv trilium-linux-x64-server /opt/trilium` you may need to remove the old version first ` sudo rm /opt/trilium/`
5. start the service back ` sudo systemctl start trilium.service `
![image](https://github.com/zadam/trilium/assets/28057767/bfddc4c8-eafd-4ef9-bb70-a4eab048b132)

No NEED to touch the trilium-data folder so you data still the same

**Comment by eliandoran** [comment]
The button to indicate updates is already there, we now need #393 for auto-updates.
