### ISSUE TITLE
(Bug report) Dockerhub `latest` tag is same as beta version

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Trilium#4590]
### Trilium Version

0.63.1

### What operating system are you using?

Ubuntu

### What is your setup?

Local (no sync)

### Operating System Version

Ubuntu

### Description

Usually with most docker images, the `latest` tag is the latest stable version (not the latest beta/alpha/etc version). 
I'm not sure if it's always been this way, but currently the latest tag on dockerhub is the beta version.

To avoid having to pin versions in the docker-compose files, it would be nice to have the `latest` version reference the latest stable version instead of the latest beta version.

**Comment by jwhonce** [comment]
@meichthys Thanks for filing the bug, I have always anchored my stable service `docker.io/zadam/trilium:0.62.5` using `latest` I may have gotten burnt.

**Comment by eroc1990** [comment]
Yeah this just bit me. I was on :latest and got downgraded (it seems) to 0.62.6, which was on an older db version. Had to bump to 0.63-latest to get myself back up and running until 0.63.x goes to stable.

**Comment by eroc1990** [comment]
@meichthys I get that, but at the same time, using :latest usually doesn't mean getting updated to a beta release when on that tag, which is what happened here. And since I caught the update at a wierd cycle where it had been upgraded to 0.63.1 and then back to 0.62.6 (downgrading the DB version in the process), it resulted in the app not starting until I put myself back on the beta release.

**Comment by eroc1990** [comment]
Historically it's been stable releases, so it was my assumption that it would stick to that. I'm guessing somehow it just got switched over to a 0.63.x beta release accidentally, because it was pretty quickly switched back to the release 0.62.x line.

**Comment by barrettsoftware** [comment]
OK so what tag should I be using instead of latest? I do not want to keep a specified version in my compose file

**Comment by sigaloid** [comment]
`wget -q https://registry.hub.docker.com/v2/repositories/zadam/trilium/tags -O - | jq -r '.results[].name' | rg -v beta | rg -v latest | rg -v buildcache | head -n1` is what I use.

Alternatively you can use the GitHub releases API to find the latest stable release.

**Comment by eroc1990** [comment]
> OK so what tag should I be using instead of latest? I do not want to keep a specified version in my compose file

If you want to stay on the 0.62.x minor version until 0.63.x is out of beta, you should be able to use `0.62-latest` to keep yourself on the latest build in this minor version. This _should_ keep you in the current stable chain, but as neither a maintainer nor contributor beyond the discussion in this thread, I don't know the roadmap for release scheduling.
