### ISSUE TITLE
(Bug report) How to change the default “codeNotesMimeTypes” ？

### ISSUE THREAD

**Issue by jinxiaoman** [TriliumNext/Trilium#4678]
### Trilium Version

0.62.6

### What operating system are you using?

centos

### What is your setup?

Local + server sync

### Operating System Version

macOS

### How to change the default “codeNotesMimeTypes” ？
> CKEditor doc The effect here,  Reference links: https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html#configuring-code-block-languages

I want to set the default codeNotesMimeTypes, 

I tried two ways: 
1. by setting the modification, I can't unsave the text.  Always selected. 
2. by modifying the sql to save only a ["text/x-markdown"]. Neither of them reach to modify the default configuration, which is plain text by default. Seeking advice on how to set the default option. 
---
<img width="628" alt="image" src="https://github.com/zadam/trilium/assets/30037936/2ba9a511-4b7e-4440-b0e4-d8009450e808">
---
<img width="437" alt="image" src="https://github.com/zadam/trilium/assets/30037936/1f74c1c6-746b-431c-afdf-c740067ec462">

**Comment by zadam** [comment]
`codeNotesMimeTypes` is an option which affects only the code notes. CKEditor is used for the text notes and its code box is not affected by this. Furthermore, Trilium does not support highlighting code in text notes (there is a plugin around for that though).
