### ISSUE TITLE
(Bug report) 500GET/api/note-map/e6aArNUM8wj3/backlink-count

### ISSUE THREAD

**Issue by Bruce-Wall** [TriliumNext/Trilium#4775]
### Trilium Version

0.63.5

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11

### Description

I have just installed trilium client and set up a trilium server, now I install trilium client on another computer and sync the data（almost just the original notes of trilium i.e. the trilium demo）, and the error indication shows up as the picture below（It's the screenshot of a random node of all the nodes of trilium demo, and clicking to any node of trilium will pop up the same Irregular intermittent error information ）

This is the error indication box poping up intermittently when clicking nodes of trilium demo:
![image](https://github.com/zadam/trilium/assets/18501962/9af4cf48-6717-438b-988c-5d593163ee8b)

There's some other information may help to detect why this error indication happens, if they don't help, please ignore them:
1.The notes: just the original trilium demo and a skin downloaded and imported from github
2. All operations before this error indication : first download the trilium client on one computer which system is Windows10, and set up the trilium server on my vps server(which system is Debian X12), then I sync them. after that I installed the lightpad skin to the trilium client by import its zip file into the trilium. then I sync them again. And then I install trilium client on another computer which system is Windows11 and sync it with my trilium server，to discover the usage of trilium I copy the trilium demo and then quickly delete it thoroughly on the Win11 PC. Then I move the lightpad skin files into a new folder note under the trilium root note on this Win11 PC. After that when I click trilium demo notes to learn how to use trilium , this error message shows up on this Win11 PC.

**Comment by Nriver** [comment]
You can search that note id `vvPD...` to find out which note goes wrong.

**Comment by perfectra1n** [comment]
I've had the demo be "weird" in the past, typically removing the demo note and starting blank works best.
