### ISSUE TITLE
(Feature request) Make first day of week configurable in options

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Trilium#4786]
### Describe feature

Since [the world is split on which day of the week is the first day](https://www.timeanddate.com/calendar/days/first-day-of-the-week.html), we should make it configurable in TriliumNext:
https://github.com/zadam/trilium/discussions/4540

**Comment by eliandoran** [comment]
@meichthys , did you mean to create this issue in the TriliumNext repo? This is the official upstream repo.
