### ISSUE TITLE
(Feature request) Support images with transparent background

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Trilium#5148]
### Describe feature

https://www.reddit.com/r/Trilium/comments/1ew21dq/transparent_layers_in_png_files/
![image](https://github.com/user-attachments/assets/22f43ec4-4989-4d32-a013-d0a359f780e3)

**Comment by SiriusXT** [comment]
Trilium itself displays transparent images, which can be achieved by adding the following custom css:
```
img.note-detail-image-view{
    background-color: #ccc;
    background-image: 
        linear-gradient(45deg, #eee 25%, transparent 25%),
        linear-gradient(-45deg, #eee 25%, transparent 25%),
        linear-gradient(45deg, transparent 75%, #eee 75%),
        linear-gradient(-45deg, transparent 75%, #eee 75%);
    background-size: 20px 20px;
    background-position: 0 0, 0 10px, 10px -10px, -10px 0px;
}
```
If you need png and other images in text notes to display a transparent background, you can try adding css:
```
img{
    background-color: #ccc;
    background-image: 
        linear-gradient(45deg, #eee 25%, transparent 25%),
        linear-gradient(-45deg, #eee 25%, transparent 25%),
        linear-gradient(45deg, transparent 75%, #eee 75%),
        linear-gradient(-45deg, transparent 75%, #eee 75%);
    background-size: 20px 20px;
    background-position: 0 0, 0 10px, 10px -10px, -10px 0px;
}
```
![图片](https://github.com/user-attachments/assets/a25912fd-0d76-4197-85be-c4231823e116)

**Comment by SiriusXT** [comment]
You can read this document to see how to add custom css:
https://github.com/TriliumNext/Docs/blob/main/Wiki/themes.md#custom-css
1：Create a css type note
![图片](https://github.com/user-attachments/assets/ab7b410d-84d1-4a72-8c9c-51695459bd8f)
2：Add a note label
![图片](https://github.com/user-attachments/assets/dd91d212-5f64-43cb-9c5a-301940f72659)
3：Add css
```
img{
    background-color: #ccc;
    background-image: 
        linear-gradient(45deg, #eee 25%, transparent 25%),
        linear-gradient(-45deg, #eee 25%, transparent 25%),
        linear-gradient(45deg, transparent 75%, #eee 75%),
        linear-gradient(-45deg, transparent 75%, #eee 75%);
    background-size: 20px 20px;
    background-position: 0 0, 0 10px, 10px -10px, -10px 0px;
}
```

![图片](https://github.com/user-attachments/assets/4a730f13-ff02-4a9e-988d-6b1a3e1a2d6d)
