### ISSUE TITLE
(Feature Request) Allowed link protocols

### ISSUE THREAD

**Issue by paulusm** [TriliumNext/trilium#5150]
### Describe feature

This issue [was raised a while back for. the legacy app](https://github.com/zadam/trilium/issues/1876), but closed as attributed to a CKEditor bug.

It looks to me like it should be possible  with current versions of CKEditor, using the allowedProtocols configuration setting

[CKEditor LinkConfig Allowed Protocols](https://ckeditor.com/docs/ckeditor5/latest/api/module_link_linkconfig-LinkConfig.html#member-allowedProtocols)

..it would be good to add zotero:// and maybe file:// as minimum, maybe to allow the user to configure their own?

### Additional Information

Example of zotero Link zotero://select/library/items/W74PPSJ8 <- nb Will only work if that item ID is in your library ...

**Comment by SiriusXT** [comment]
I added `allowedProtocols: [ 'https?', 'zotero', 'file']` in `Notes/libraries/ckeditor/ckeditor.js` according to the [CKEditor 5 documentation](https://ckeditor.com/docs/ckeditor5/latest/features/link.html#adding-custom-protocols-in-links), which allows links to navigate to file or Zotero.
![图片](https://github.com/user-attachments/assets/f398b9ff-847c-4449-a3a9-8a50f344ddcb)
![图片](https://github.com/user-attachments/assets/ed7f27fd-982b-450b-962b-074b9477f9f0)
