### ISSUE TITLE
(Bug report) Web clipper "save link with a note", cannot see the link in android mobile view

### ISSUE THREAD

**Issue by ckholy2** [TriliumNext/trilium#5198]
### TriliumNext Version

0.90.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 22H2

### Description

Under winodws, when I use "web clipper" to "save link with a note",
the url link is stored in #pageUrl which can be viewed in browser normal desktop view.
However, if in android phone under "mobile view", this url link can't be seen. (need to switch of desktop view)

**Comment by eliandoran** [comment]
Done in #8615.
