### ISSUE TITLE
(Bug report) toggleTray: Restore from system tray via custom hotkey does not work

### ISSUE THREAD

**Issue by megabugman** [TriliumNext/trilium#5230]
**TriliumNext Version**

0.90.8 & 0.90.9-beta

**What operating system are you using?**

Windows

**What is your setup?**

Local (no sync)

**Operating System Version**

Windows 10 Version 10.0.19045  &
Windows 11 Version 10.0.2.22631

**Description**

Using toggleTray to minimize to tray works, but restore does not.
I tried many Hotkeys, none work. For instance Ctrl+Shift+J will minimize to tray, but pressing the hotkey again won't restore the application. Clicking the icon manually in the system tray will restore the window as expected. Confirmed on Windows 10 & 11.

![restore_bug](https://github.com/user-attachments/assets/a45cb85d-353b-4ce5-a151-2bc98abb6a30)

**Comment by SiriusXT** [comment]
You need to add `glabal:` in front of the shortcut key, and then restart trilium completely.
![图片](https://github.com/user-attachments/assets/3120895b-825a-4816-b24b-a35f59fc0d57)

**Comment by megabugman** [comment]
Thank You SiriusXT! It works now.

I think, this should be mentioned in the description 
![image](https://github.com/user-attachments/assets/e5b9ee8a-a44e-4410-85fc-5ef43411a328)
as "Reload app to apply changes" does not work.

Thanks again. 👍
