### ISSUE TITLE
(Bug report) Make "Open New Window" actually open a new window in the web app

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Trilium#5270]
### Describe feature

Currently, the "Open New Window" button (in the web app) doesn't open a new window, but rather opens a new tab in the browser.

![image](https://github.com/user-attachments/assets/69d613cc-3ce3-4074-98d8-3476d8e21872)

We should make this menu item actually open Trilium in a [new browser window](https://stackoverflow.com/questions/14132122/open-url-in-new-window-with-javascript) rather than a new tab.

Alternatively, we could just rename the menu item to "Open New Tab" for the web app.

**Comment by SiriusXT** [comment]
When I tested on Firefox and Edge, new windows like this were opened:
![图片](https://github.com/user-attachments/assets/eea49519-2499-4db7-bb7c-7694cd733c8a)

Check that the code is also the code for the new window,
![图片](https://github.com/user-attachments/assets/25ca4e63-df07-4d95-bf2c-9b1c987352ec)

I just accidentally clicked on closed this issue

Could it be a browser difference?
