### ISSUE TITLE
More shortcuts on ckeditor5

### ISSUE THREAD

**Issue by nil0x42** [TriliumNext/Trilium#693]
It would greatly improve usability if we have more shortcuts for ckeditor styling.
For example:
ctrl + 1,2,3 for `<h1>`, `<h2>`, `<h3>`
ctrl + 0 for normal text size (of for reseting all styling)
etc...

Also, i compulsively use "front color = red" and "front color = green", to help me easily see positive and negative properties of something.
So if there is any way to do styling from a ckeditor API, it would be very interesting to make it available on scripting API.

**Comment by zadam** [comment]
For some of these there's markdown-like [autoformat](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html) - e.g. for h3 you just type `### `

**Comment by nil0x42** [comment]
Yes i use them a lot !
But i'm a very mind-changing guy, so i keep changing a previous formatting differently all time.
An i would like to be able to select my `<h2>` line and convert it to something else without clicking on the ckeditor widget, to select formatting from the list.

Of course this might be specific to my own use case, that's why my other issue https://github.com/zadam/trilium/issues/701 is probably a better way to handle things, at it would allow anyone to interact with ckeditor at it's own risks.

**Comment by safesparrow** [comment]
I would also find shortcuts for headings and other ckeditor features very useful - especially given the formatting panel is hidden by default.
@zadam do you have any plans for this issue or the linked #701 ?

**Comment by zadam** [comment]
Yes, I would like to add more shortcuts, it's just not highest priority ATM.

**Comment by shotcollin** [comment]
I was just about to add my own feature request for a shortcut to change a selected paragraph to a heading, and I was thinking something similar to @nil0x42's suggestion of `ctrl` + `1` for `<h1>` etc. I'm sure such a feature would be profoundly appreciated by all of us who will do almost anything humanly possible not to have to move our hand from the keyboad *all the way* over to the mouse.

I also noticed Issue #2234 and it seems like this feature might also address that as well? Assuming there were shortcuts for both headings and regular paragraph.

In any case, thanks for the excellent work @zadam!

**Comment by Birdacious** [comment]
The script posted in #2954 adds shortcuts for font color and heading style (and I think could be extended for other CKEditor commands, if you check out the CKEditor docs). Hope this helps!

**Comment by eliandoran** [comment]
Duplicate of #4129 for the heading shortcuts; the font-colour half is tracked in #988.
