### ISSUE TITLE
Keyboard Shortcut for Paragraph Style/Edit Block

### ISSUE THREAD

**Issue by joshcsullivan** [TriliumNext/Trilium#764]
Would it be possible to add a keyboard shortcut option to open the Paragraph Style/Edit Block?

Once opened the Edit Block options are keyboard navigable/selectable, but invoking the edit block with the mouse is causing some friction when formatting notes.

Cheers,
Josh

**Comment by eliandoran** [comment]
This is now indirectly supported via slash commands, where you can type /h2, /h3, /paragraph to apply to the current block.
